spring:
  datasource:
    url: jdbc:mysql://localhost:3306/daroomi_local?useSSL=false&serverTimezone=UTC
    username: root
    password: kjh19980303@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

